# Generated by Django 5.2.14 on 2026-05-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('owner', 'Owner'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
