# Generated by Django 5.2.14 on 2026-05-31 21:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import property.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('draft', 'Draft')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nearby_colleges', models.ManyToManyField(blank=True, related_name='nearby_properties', to='college.college')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=property.models.property_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='property_pr_status_b98bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='property_pr_city_650e24_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state'], name='property_pr_state_42055c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent'], name='property_pr_rent_5b8818_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='property_pr_propert_1a0342_idx'),
        ),
    ]
